# general content

title: Blog Chema
email: jmnavarrogomez@gmail.com
description: Chema Navarro blog
baseurl: "/blog" # /erreza
url: "https://arqueochema.github.io/blog" # https://gruncho.github.io/erreza

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Sass settings

sass:
  sass_dir: assets/scss
  style: :compressed

# Gems

plugins:
  - jekyll-feed

authors:
  gruncho:
    name: gruncho
